language: node_js
node_js: node
cache:
  directories:
    - node_modules
services: postgresql
before_script:
  - sudo apt-get -qq update # qq for less output
install:
  - yarn
  - yarn buildEnv
  - yarn setup:server
  - yarn setup:client
script:
  - yarn build # develop with webpack
  - sleep 10
  - yarn start:server # start the static webserver
  - zip -r latest *
  - mkdir -p dpl_cd_upload_ui
  - mv latest.zip dpl_cd_upload_ui/latest.zip
<<<<<<< HEAD
<<<<<<< HEAD

<<<<<<< HEAD
=======
>>>>>>> [travis] testing: deploy to s3
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    skip_cleanup: true # prevents resetting and deleting all changes
<<<<<<< HEAD
        on: &2
      repo: KevinDavidBrian/codesling.io-ui
    bucket: 'kdb-legacy-ui'
    # region: us-west-1
=======
    on: &2
      repo: KevinDavidBrian/codesling.io-api
    bucket: kdb-legacy-api
>>>>>>> [travis] testing: deploy to s3
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: kdb-legacy-api
    key: latest.zip
    bundle_type: zip
<<<<<<< HEAD
    application: 'kdb-legacy-ui'
    deployment_group: kdbDeploymentGroupe
    region: us-west-1b
    on: *2
=======
# deploy:
#   - provider: s3
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#     skip_cleanup: true # prevents resetting and deleting all changes
#         on: &2
#       repo: KevinDavidBrian/codesling.io-api
#     bucket: 'kdb-legacy-ui'
#     # region: us-west-1
#   - provider: codedeploy
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#     bucket: kdb-legacy-api
#     key: latest.zip
#     bundle_type: zip
#     application: 'kdb-legacy-ui'
#     deployment_group: kdbDeploymentGroupe
#     region: us-west-1b
#     on: *2
>>>>>>> [travis] - recraete error on travis file
=======
>>>>>>> [travis] - recraete error travais
=======
    application: kdb-legacy-api
    deployment_group: kdbDeploymentGroupe
    region: us-west-1b
    on: *2
>>>>>>> [travis] testing: deploy to s3
