language: node_js
node_js: node
cache:
  directories:
    - node_modules
before_script:
  - sudo apt-get -qq update # qq for less output
install:
  - yarn
  - yarn buildEnv
  - yarn setup:server
  - yarn setup:client
script:
  - yarn build # develop with webpack
  - yarn start:server # start the static webserver
  - zip -r latest *
  - mkdir -p dpl_cd_upload_ui
  - mv latest.zip dpl_cd_upload_ui/latest.zip
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  skip_cleanup: true # prevents resetting and deleting all changes
  on: &2
    repo: KevinDavidBrian/codesling.io-api
  bucket: kdb-legacy-api
  provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: kdb-legacy-api
  key: latest.zip
  bundle_type: zip
  application: kdb-legacy-api
  deployment_group: kdbDeploymentGroupe
  region: us-west-1b
  on: *2