language: node_js
node_js: node
cache:
  directories:
    - node_modules
services: postgresql
before_script:
  - sudo apt-get -qq update # qq for less output
  # - psql -c 'create database travis_ci_test;' -U root
install:
  - yarn
  - yarn buildEnv
  - yarn setup:server
  - yarn setup:client
script:
  - yarn build # develop with webpack
  - yarn start:server # start the static webserver
  - zip -r latest *
  - mkdir -p dpl_cd_upload_ui
  - mv latest.zip dpl_cd_upload_ui/latest.zip
